<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SimplePLC.Domain\SimplePLC.Domain.csproj" />
    <ProjectReference Include="..\SimplePLC.Protocol\SimplePLC.Protocol.csproj" />
  </ItemGroup>

</Project>
