<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SimplePLC.Protocol\SimplePLC.Protocol.csproj" />
    <ProjectReference Include="..\SimplePLC.Domain\SimplePLC.Domain.csproj" />
    <ProjectReference Include="..\SimplePLC.Application\SimplePLC.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Ports" Version="8.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
